### ISSUE TITLE
Add instructions on how to deploy without using Serverless

### ISSUE THREAD

**Issue by ejstembler** [BranLiang/aws-ruby-lambda-layer#1]
It may be as simple as running `build.sh` and then zipping the container file for upload to AWS Lambda console?

**Comment by mlsaito** [comment]
@ejstembler Same sentiment. I was able to do something like this:

1. Execute `./build.sh`
2. Change directory inside `layer` folder and generate zip
```
$ zip -r layer.zip ./ruby/ ./lib -x ./ruby/2.5.0/cache/\*
```
3. Publish version via the generated zip file
```
$ aws lambda publish-layer-version \
         --layer-name ruby-kubectl-pg \
         --region us-east-1 \
         --compatible-runtimes ruby2.5 \
         --zip-file fileb://layer.zip
```

Hope this helps.

**Comment by mlsaito** [comment]
@BranLiang I created a PR https://github.com/BranLiang/aws-ruby-lambda-layer/pull/2 which adds manually deploying the layer via AWS CLI. It would be great if you could check. Thanks!

**Update:** And thanks a lot for making this. Really made my life easier.

**Comment by BranLiang** [comment]
@mlsaito Thanks for the pr, already merged
